name: Build/release

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - run: yarn
      - run: yarn build

      - name: Archive
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: ./dist
          files: |
            index.html
            assets
          outPath: waffle.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: waffle.tar.gz
